const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
const skills={Programming:['Python','C++','C','Java','JavaScript'],ML:['PyTorch','TensorFlow','Transformers','Keras','LLM Applications','NLTK'],Data:['NumPy','Pandas','SQL','Matplotlib'],Backend:['FastAPI','Flask','Django','Node.js','Docker','Kubernetes','Linux','Redis','GraphQL','CUDA']};
const projects=[['LLM From Scratch',['Self-attention','Multi-head attention','Positional encoding','Training pipeline','Inference pipeline'],['Python','PyTorch']],['Pune Temperature Forecasting',['LSTM forecasting','Time-series prediction','Data preprocessing','Regression metrics'],['Python','TensorFlow']],['Genetic Algorithm Biped Simulation',['Evolutionary optimization','Physics simulation','Autonomous gait evolution'],['Python']],['Computer Vision Experiments',['CNNs','Image classification','Feature extraction','Data augmentation'],['Python','PyTorch']]];
const timeline=['AI Projects','CUDA Experiments','NLP Applications','Systems Programming','Operating Systems','Data Processing'];
function initContent(){const sg=$('#skillsGrid');Object.entries(skills).forEach(([cat,items],i)=>{sg.insertAdjacentHTML('beforeend',`<article class="skill-card reveal" style="--level:${88-i*7}%"><p class="label">0${i+1}</p><h3>${cat}</h3><div class="skill-list">${items.map(x=>`<span class="chip">${x}</span>`).join('')}</div><div class="skill-bar"><span></span></div></article>`)});const pg=$('#projectGrid');projects.forEach((p,i)=>pg.insertAdjacentHTML('beforeend',`<article class="project-card reveal"><p class="label">Project 0${i+1}</p><h3>${p[0]}</h3><ul>${p[1].map(f=>`<li>${f}</li>`).join('')}</ul><div class="skill-list">${p[2].map(t=>`<span class="chip">${t}</span>`).join('')}</div></article>`));const tl=$('#timelineList');timeline.forEach((t,i)=>tl.insertAdjacentHTML('beforeend',`<article class="timeline-item reveal"><p class="label">Milestone 0${i+1}</p><h3>${t}</h3><p>Explored ${t.toLowerCase()} through hands-on experiments, readable implementations, and research-driven iteration.</p></article>`));$('#year').textContent=new Date().getFullYear();}
function initForm(){const form=$('#contactForm'),status=$('#formStatus');form.addEventListener('submit',e=>{e.preventDefault();if(!form.checkValidity()){status.textContent='Please complete all fields with a valid email and message.';status.style.color='#fca5a5';form.reportValidity();return}status.textContent='Message validated. Please send via your email client or connect on LinkedIn/GitHub.';status.style.color='#67e8f9';form.reset();});}
function initCards(){document.addEventListener('pointermove',e=>{$$('.project-card').forEach(card=>{const r=card.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;card.style.setProperty('--mx',`${x}px`);card.style.setProperty('--my',`${y}px`);if(x>=0&&y>=0&&x<=r.width&&y<=r.height){const rx=(y/r.height-.5)*-8,ry=(x/r.width-.5)*10;card.style.transform=`perspective(900px) rotateX(${rx}deg) rotateY(${ry}deg) translateY(-6px)`}else card.style.transform='';});});}
window.addEventListener('load',()=>setTimeout(()=>$('#loader').classList.add('hidden'),450));
document.addEventListener('DOMContentLoaded',()=>{initContent();initForm();initCards();});
