export const profile = { name: 'Pranit Dhanade', role: 'Machine Learning Engineer • AI Researcher • Computer Science Student', location: 'Pune, Maharashtra, India', email: 'pranit.dhanade@example.com', github: 'https://github.com/pranitdhanade-sys', linkedin: 'https://www.linkedin.com/in/pranit-dhanade/' };
export const links = [{ label: 'GitHub', href: profile.github }, { label: 'LeetCode', href: 'https://leetcode.com/' }, { label: 'Codeforces', href: 'https://codeforces.com/' }, { label: 'CodeChef', href: 'https://www.codechef.com/' }, { label: 'GeeksforGeeks', href: 'https://www.geeksforgeeks.org/' }];
export const projects = [
 { title: 'LLM From Scratch', folder: 'LLM_FROM_SCRATCH', desc: 'Transformer architecture from first principles with self-attention, multi-head attention, positional encoding, training and inference pipelines.', tech: ['Python','PyTorch'], href: '#' },
 { title: 'Pune Temperature Forecasting', folder: 'PUNE_TEMP_LSTM', desc: 'LSTM time-series forecasting system using sequence windowing, feature engineering and regression evaluation.', tech: ['Python','TensorFlow'], href: '#' },
 { title: 'Genetic Algorithm Biped Simulation', folder: 'GA_BIPED_SIM', desc: 'Evolutionary optimization for autonomous gait evolution with physics simulation and fitness functions.', tech: ['Python'], href: '#' },
 { title: 'Computer Vision Experiments', folder: 'CV_EXPERIMENTS', desc: 'CNN training, image classification, feature extraction and augmentation experiments.', tech: ['Python','PyTorch'], href: '#' }
];
export const skillGroups = { Programming: ['Python','C++','C','Java','JavaScript'], 'ML & AI': ['PyTorch','TensorFlow','Transformers','LLM Applications','Keras','NLTK'], 'Data Science': ['NumPy','Pandas','SQL','Matplotlib','Statistical Analysis'], 'Systems & Backend': ['FastAPI','Flask','Django','Node.js','Docker','Kubernetes','Linux','Redis','GraphQL','CUDA'] };
export const timeline = ['AI Projects','Systems Programming','CUDA Experiments','Operating Systems Work','Large-scale Data Processing','AI Assistants','NLP Applications'];
export const interests = ['LLMs','AI Agents','Computer Vision','Deep Learning','Optimization','Reinforcement Learning','Multi-Agent Systems'];
